### ISSUE TITLE
The execution order of the code

### ISSUE THREAD

**Issue by liyunkai-carpediem** [fepegar/resector#14]
* resector version: 0.2.10
* Python version:3.7
* Operating System:linux

### Description

I want to delve into the code and not run it as pre-packaged methods. I have found the generated geodesic polyhedron and I would like to ask which part of the code is responsible for adding simplex noise to it , as well as the code for random affine transformations.

**Comment by fepegar** [comment]
Hi @liyunkai-carpediem. You can just search for the code:

https://github.com/fepegar/resector/blob/ed63b3de5562fb011fb88916c4da8d170415cd6f/resector/mesh.py#L64-L87

https://github.com/fepegar/resector/blob/ed63b3de5562fb011fb88916c4da8d170415cd6f/resector/mesh.py#L109-L124

**Comment by liyunkai-carpediem** [comment]
Dear sir, 
Thanks a lot for giving me an answer, I am very excited!!!
And I have found the relative codes in the following path: "scripts/test/perlin_sphere.py"
I think they are the same(?)

1. So what is the difference between the folder "scripts" and "resector"?
2. I have found there is a code called "perlin_image.py",  I ran it, getting a result of"simplex.nii", maybe it is a noise for adding it into the sphere? But I noticed that we use “noise” library to do so. So what is the function of "perlin_image.py"?
3.  when I run the following code, I have noticed that there are 5 shapes generated. Which one will be the final shape I will be used later?
```
for _ in range(5):
    offset = np.random.randint(1000)
    output_path = f'/tmp/geodesic_polyhedron_noise_{offset}.vtp'

    volume = np.random.randint(100, 10000)
    center = np.random.randint(-50, 50, size=(3))
    k = 4/3 * np.pi
    radius = (volume / k) ** (1/3)
    ratio = np.random.uniform(0.8, 1)
    a = radius
    b = radius * ratio
    c = radius / ratio
    radii = a, b, c
    angles = np.random.uniform(0, 180, size=3)

    output_poly_data = get_resection_poly_data(
        input_poly_data,
        offset,
        center,
        radii,
        angles,
    )
```
4. I found that the size of the shape is not mentioned in the paper, so how to change the size of shape I generated to fit my own data?
Thanks a lot.

**Comment by liyunkai-carpediem** [comment]
When I run the mesh_to_vol, I met some problems.
My code is here:
```
from resector.io import read_poly_data, write
from resector.mesh import mesh_to_volume

mesh_path = '/storage/liyunkai/resector-master/geodesic_polyhedron_noise_102.vtp'
reference_path = '/storage/liyunkai/MICCAI_FeTS2022_TrainingData/FeTS2022_00000/FeTS2022_00000_seg.nii.gz'

poly_data = read_poly_data(mesh_path)

image = mesh_to_volume(poly_data, reference_path)
write(image, '/storage/liyunkai/resector-master/result/stenciled.nii.gz')
```
And the error is:


```
/home/liyunkai/anaconda3/envs/resenv/bin/python3.8 /storage/liyunkai/resector-master/scripts/test/mesh_to_vol.py 
Traceback (most recent call last):
  File "/storage/liyunkai/resector-master/resector/mesh.py", line 181, in mesh_to_volume
    write(subvolume, reference_path)  # TODO: use an existing image
  File "/storage/liyunkai/resector-master/resector/io.py", line 50, in write
    sitk.WriteImage(image, image_path)
  File "/home/liyunkai/anaconda3/envs/resenv/lib/python3.8/site-packages/SimpleITK/extra.py", line 425, in WriteImage
    return writer.Execute(image)
  File "/home/liyunkai/anaconda3/envs/resenv/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 7907, in Execute
    return _SimpleITK.ImageFileWriter_Execute(self, *args)
RuntimeError: Exception thrown in SimpleITK ImageFileWriter_Execute: /tmp/SimpleITK-build/ITK-prefix/include/ITK-5.3/itkImageFileWriter.hxx:245:
ITK ERROR: ImageFileWriter(0x7acf7c0): Largest possible region does not fully contain requested paste IO region. Paste IO region: ImageIORegion (0x7ffefcd3d200)
  Dimension: 3
  Index: 0 0 0 
  Size: 0 0 18 
Largest possible region: ImageRegion (0x7ffefcd3d140)
  Dimension: 3
  Index: [0, 0, 0]
  Size: [0, 0, 18]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/liyunkai/resector-master/scripts/test/mesh_to_vol.py", line 9, in <module>
    image = mesh_to_volume(poly_data, reference_path)
  File "/storage/liyunkai/resector-master/resector/mesh.py", line 187, in mesh_to_volume
    write(reference, error_image_path)
  File "/storage/liyunkai/resector-master/resector/io.py", line 50, in write
    sitk.WriteImage(image, image_path)
  File "/home/liyunkai/anaconda3/envs/resenv/lib/python3.8/site-packages/SimpleITK/extra.py", line 425, in WriteImage
    return writer.Execute(image)
  File "/home/liyunkai/anaconda3/envs/resenv/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 7907, in Execute
    return _SimpleITK.ImageFileWriter_Execute(self, *args)
TypeError: Wrong number or type of arguments for overloaded function 'ImageFileWriter_Execute'.
  Possible C/C++ prototypes are:
    itk::simple::ImageFileWriter::Execute(itk::simple::Image const &)
    itk::simple::ImageFileWriter::Execute(itk::simple::Image const &,std::string const &,bool,int)


Process finished with exit code 1

```
