### ISSUE TITLE
Pixel type: vector of 8-bit unsigned integer is not supported in 3D byclass itk::simple::GreaterImageFilter

### ISSUE THREAD

**Issue by fepegar** [fepegar/resector#5]
* resector version: 0.2.7
* Python version: 3.8
* Operating System: Windows

```python
(torchio) λ resect t1.nii.gz 13734_LabSeg_Segmentation.nii.gz t1_resected.nii.gz t1_label.nii.gz
Traceback (most recent call last):
  File "C:\Users\fernando\Miniconda3\envs\torchio\Scripts\resect-script.py", line 33, in <module>
    sys.exit(load_entry_point('resector', 'console_scripts', 'resect')())
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\fernando\git\resector\resector\cli\resect.py", line 57, in main
    resectable_paths, gm_paths, noise_path, existed = ensure_images(
  File "c:\users\fernando\git\resector\resector\cli\resect.py", line 125, in ensure_images
    gm = resector.parcellation.get_gray_matter_mask(
  File "c:\users\fernando\git\resector\resector\parcellation.py", line 56, in get_gray_matter_mask
    mask = nib_to_sitk(array, parcellation_nii.affine) > 0
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\SimpleITK\SimpleITK.py", line 4488, in __gt__
    return Greater( self, float(other) )
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\SimpleITK\SimpleITK.py", line 34900, in Greater
    return _SimpleITK.Greater(*args)
RuntimeError: Exception thrown in SimpleITK Greater: d:\a\1\sitk\code\common\include\sitkMemberFunctionFactory.hxx:196:
sitk::ERROR: Pixel type: vector of 8-bit unsigned integer is not supported in 3D byclass itk::simple::GreaterImageFilter
```

**Comment by fepegar** [comment]
This happened because I was using a 4D image as input, instead as a GIF parcellation.
