### ISSUE TITLE
nibabel.filebasedimages.ImageFileError: Empty file

### ISSUE THREAD

**Issue by fepegar** [fepegar/resector#6]
```python
** ERROR (nifti_image_write_hdr_img2): cannot open output file 'C:\Users\fernando\AppData\Local\Temp\tmpo_staroz.nii'
Traceback (most recent call last):
  File "C:\Users\fernando\Miniconda3\envs\torchio\Scripts\resect-script.py", line 33, in <module>
    sys.exit(load_entry_point('resector', 'console_scripts', 'resect')())
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\fernando\git\resector\resector\cli\resect.py", line 93, in main
    transformed = transform(subject)
  File "c:\users\fernando\git\torchio\torchio\transforms\transform.py", line 126, in __call__
    transformed = self.apply_transform(subject)
  File "c:\users\fernando\git\torchio\torchio\transforms\augmentation\composition.py", line 47, in apply_transform
    subject = transform(subject)
  File "c:\users\fernando\git\resector\resector\random_resection.py", line 110, in __call__
    results = resect(
  File "c:\users\fernando\git\resector\resector\resector.py", line 65, in resect
    raw_resection_mask = mesh_to_volume(
  File "c:\users\fernando\git\resector\resector\mesh.py", line 180, in mesh_to_volume
    write(subvolume, reference_path)  # TODO: use an existing image
  File "c:\users\fernando\git\resector\resector\io.py", line 54, in write
    nii = nib.load(image_path)
  File "C:\Users\fernando\Miniconda3\envs\torchio\lib\site-packages\nibabel\loadsave.py", line 46, in load
    raise ImageFileError(f"Empty file: '{filename}'")
nibabel.filebasedimages.ImageFileError: Empty file: 'C:\Users\fernando\AppData\Local\Temp\tmpo_staroz.nii'
```

**Comment by panchel** [comment]
Hi again! Yes, thanks so much for working on this issue. I am also getting that exact error:

![image](https://user-images.githubusercontent.com/86067371/123018511-af0a9f80-d39c-11eb-8aac-1098a8dbd427.png)

I have been able to install macOS Catalina 10.15 on VMWare. Should resector be able to properly run on VMWare?

**Comment by fepegar** [comment]
Yes, it should! And I've used it on macOS many times. At the moment I don't have much access to Windows to work on this, but I'll keep you posted.

**Comment by panchel** [comment]
Great, thanks! It looks like it is completely working on VMWare, so I will continue to use that for now. Thanks again, and please let me know if there's anything I can do to help.

**Comment by fepegar** [comment]
Great! Thanks for the update.

**Comment by fepegar** [comment]
Closing as stale.
